Dokujunkies_Geschichtepolitik:
    feed: "http://dokujunkies.org/dokus/geschichtepolitik/feed"
    blacklist:
      - Papst
      - Mittelalter
    quality: 720p
    downloadfolder: /share/Web/temp/Dokus
    hoster: uploaded
RMZ_Shows:
    feed: "http://rmz.cr/feed"
    shows:
      - The Tom And Jerry Show
      - The Blacklist
      - Strike Back
    quality: 1080p
    downloadfolder: /volume1/SHAREDFOLDER/test
    hosterShort: /UL
    hosterName: uploaded
RMZ_Movies:
    feed: "http://rmz.cr/feed"
    movies:
      - Free Solo
      - The Irishman
    quality: 1080p
    downloadfolder: /share/Web/temp/TV-Shows
    hosterShort: /UL
    hosterName: uploaded
CRE:
    feed: "http://cre.fm/feed/m4a/"
    downloadfolder: /share/Web/temp/Audio/cre
