Dokujunkies_Geschichtepolitik:
    feed: "http://dokujunkies.org/dokus/geschichtepolitik/feed"
    blacklist:
      - Papst
      - Mittelalter
    quality: 720p
    downloadfolder: /share/Web/temp/Dokus
    hoster: uploaded
RMZ_Shows:
    feed: "http://rmz.cr/feed"
    shows:
      - Young Sheldon
      - Brooklyn Nine Nine
      - The Good Doctor
      - Lethal Weapon
      - The Big Bang Theory
      - The Orville
    quality: 1080p
    downloadfolder: /volume1/server/00_Incoming/00_download/
    hosterShort: /UL
    hosterName: uploaded    
CRE:
    feed: "http://cre.fm/feed/m4a/"
    downloadfolder: /share/Web/temp/Audio/cre
